plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.readingforest'
version = '0.1.0'

android {
  namespace "expo.modules.rfongoingtimer"
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation 'androidx.core:core:1.17.0'
}
