export const palette = {
  leaf: '#8BCB6B',
  leafDeep: '#5FA85A',
  leafShadow: '#4C8A47',
  leafSoft: '#DDF1CF',
  wood: '#C9A47E',
  woodDeep: '#A07B55',
  woodShadow: '#82603F',
  woodSoft: '#F1E3CF',
  beige: '#FBF5E6',
  cream: '#FFFDF6',
  sand: '#F4EAD3',
  sky: '#9ED8F0',
  skyDeep: '#5FB4D9',
  skySoft: '#DDF2FB',
  peach: '#F9C9A6',
  peachDeep: '#E7A174',
  pink: '#F7B7C5',
  pinkDeep: '#E58AA0',
  pinkSoft: '#FDE6EC',
  yellow: '#F9DC7A',
  yellowDeep: '#E2B947',
  yellowSoft: '#FDF3CC',
  lavender: '#CDBBF0',
  stone: '#C9BFB0',
  stoneDeep: '#A3978A',
  stoneSoft: '#EEE9E1',
  brown: '#5B4636',
  brownSoft: '#9A8673',
  white: '#FFFFFF',
  danger: '#E77B6E',
  dangerDeep: '#C45C50',
} as const;

export const colors = {
  background: palette.beige,
  backgroundAlt: palette.sand,
  surface: palette.cream,
  surfaceMuted: palette.woodSoft,
  border: '#EADFC8',
  text: palette.brown,
  textMuted: palette.brownSoft,
  textOnPrimary: palette.white,
  primary: palette.leaf,
  primaryDeep: palette.leafDeep,
  primaryShadow: palette.leafShadow,
  primarySoft: palette.leafSoft,
  accent: palette.wood,
  accentShadow: palette.woodShadow,
  star: palette.yellowDeep,
  heart: palette.pinkDeep,
  danger: palette.danger,
  dangerShadow: palette.dangerDeep,
  overlay: 'rgba(91, 70, 54, 0.35)',
} as const;

export type ColorName = keyof typeof colors;
